version: "3.9"

services:
  sample_service:
    build:
      context: ./sample
      network: host
    image: sample_service:local
    container_name: sample_service_container
    environment:
      FLASK_APP: ${SAMPLE_SERVICE_APP_NAME:-sample_service}
      DEBUG: ${SAMPLE_SERVICE_DEBUG:-True}

      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
      KAFKA_CONSUMER_USERNAME: ${KAFKA_CONSUMER_USERNAME}
      KAFKA_CONSUMER_PASSWORD: ${KAFKA_CONSUMER_PASSWORD}
      KAFKA_CONSUMER_GROUP: ${KAFKA_CONSUMER_GROUP}
      KAFKA_SOURCE_TOPIC: ${KAFKA_SOURCE_TOPIC}
      KAFKA_DESTINATION_TOPIC: ${KAFKA_STG_SERVICE_ORDERS_TOPIC}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    network_mode: "bridge"
    ports:
      - "5101:5000"
    restart: unless-stopped
